import Head from 'next/head';

import styles from './Home.module.scss';
import Banner from './sections/Banner/Banner';
import Beneficios from './sections/Beneficios/Beneficios';
import ExAluno from './sections/ExAluno/ExAluno';
import Footer from './sections/Footer/Footer';
import JaFazParte from './sections/JaFazParte/JaFazParte';
// import Menu from './sections/Menu/Menu';
import OqueE from './sections/OqueE/OqueE';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Afya Ventures</title>
        <meta name="description' content='Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Menu /> */}
      <Banner />
      <main className={styles.main}>
        <OqueE />
        <Beneficios />
        <ExAluno />
        <JaFazParte />
        <Footer />
      </main>
    </div>
  );
}
